feed:
  type: zillionare
  filefeed:
    bars_path: /apps/backtest/tests/data/bars_1m.pkl
    limits_path: /apps/backtest/tests/data/limits.pkl
redis:
  dsn: redis://localhost:6379
postgres:
  dsn: postgres://zillionare:123456@localhost:5432/zillionare
  enabled: true

influxdb:
  url: http://localhost:8086
  token: my-token
  org: my-org
  bucket_name: my-bucket
  enable_compress: true
