# vim:set ft=dockerfile:
FROM ubuntu:20.04
WORKDIR /
COPY rootfs ./
VOLUME config

ARG version
ARG pypi=https://pypi.tuna.tsinghua.edu.cn/simple
ARG wheel
ENV DEBIAN_FRONTEND=noninteractive
ENV PORT=7080

RUN sed -i s/archive.ubuntu.com/mirrors.aliyun.com/g /etc/apt/sources.list \
    && sed -i s/security.ubuntu.com/mirrors.aliyun.com/g /etc/apt/sources.list \
    && apt-get update \
    && apt-get -qq install -y --no-install-recommends python3.8 python3-pip build-essential python3.8-dev vim iputils-ping wget tzdata \
    && pip3 config set global.index-url ${pypi} \
    && pip3 install cython \
    && pip3 install numpy==1.22.3 \
    && pip3 install "zillionare-omicron>=2.0.0.0.a27" --pre --default-timeout=300 \
    && pip3 install ${wheel} --default-timeout=300 \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /var/log/backtest

EXPOSE $PORT
ENTRYPOINT ["/root/zillionare/entrypoint.sh"]
