# vim:set ft=dockerfile:
FROM ubuntu:20.04
WORKDIR /
COPY rootfs ./
VOLUME config

ENV DEBIAN_FRONTEND=noninteractive
ENV PORT=7080

RUN    apt-get update\
    && apt-get -qq install -y --no-install-recommends python3.8 python3-pip build-essential python3.8-dev vim iputils-ping wget tzdata \
    && pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    && pip3 install cython \
    && pip3 install numpy==1.22.3 \
    && pip3 install --pre zillionare-omicron \
    && pip3 install --pre zillionare-backtest -i https://pypi.org/simple \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /var/log/backtest

EXPOSE $PORT
ENTRYPOINT ["/root/zillionare/entrypoint.sh"]
